"""empty message

Revision ID: 245c3aabd51b
Revises: 
Create Date: 2024-01-29 01:39:59.388427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245c3aabd51b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_captcha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('captcha', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_point',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('knowledge_point_name', sa.String(length=255), nullable=False),
    sa.Column('knowledge_parent_point', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('school', sa.String(length=100), nullable=False),
    sa.Column('major', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('avatar', sa.String(length=100), nullable=False),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('question_answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('question_path', sa.String(length=255), nullable=False),
    sa.Column('answer_path', sa.String(length=255), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('knowledge_point', sa.Integer(), nullable=True),
    sa.Column('question_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_point'], ['knowledge_point.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_answer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('favorite', sa.Integer(), nullable=True),
    sa.Column('wrong_question', sa.Integer(), nullable=True),
    sa.Column('user_answer_path', sa.String(length=255), nullable=True),
    sa.Column('user_answer_content', sa.String(length=255), nullable=True),
    sa.Column('record_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_answer_id'], ['question_answer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    op.drop_table('question_answer')
    op.drop_table('user')
    op.drop_table('knowledge_point')
    op.drop_table('email_captcha')
    # ### end Alembic commands ###
