"""empty message

Revision ID: 28e713078a57
Revises: 245c3aabd51b
Create Date: 2024-01-31 00:36:36.080444

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28e713078a57'
down_revision = '245c3aabd51b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_captcha', schema=None) as batch_op:
        batch_op.alter_column('captcha',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('knowledge_point', schema=None) as batch_op:
        batch_op.alter_column('knowledge_point_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('question_answer', schema=None) as batch_op:
        batch_op.alter_column('question_path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('answer_path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('school',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('major',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('avatar',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('avatar',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('major',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('school',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('question_answer', schema=None) as batch_op:
        batch_op.alter_column('answer_path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('question_path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('knowledge_point', schema=None) as batch_op:
        batch_op.alter_column('knowledge_point_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('email_captcha', schema=None) as batch_op:
        batch_op.alter_column('captcha',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
