"""empty message

Revision ID: 5e24eb9cf89d
Revises: d00a47e58fa8
Create Date: 2024-01-29 00:48:12.863089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e24eb9cf89d'
down_revision = 'd00a47e58fa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_point',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('knowledge_point_name', sa.String(length=255), nullable=False),
    sa.Column('knowledge_parent_point', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('question_path', sa.String(length=255), nullable=False),
    sa.Column('answer_path', sa.String(length=255), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('knowledge_point', sa.Integer(), nullable=True),
    sa.Column('question_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_point'], ['knowledge_point.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_answer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('favorite', sa.Integer(), nullable=True),
    sa.Column('wrong_question', sa.Integer(), nullable=True),
    sa.Column('user_answer_path', sa.String(length=255), nullable=True),
    sa.Column('user_answer_content', sa.String(length=255), nullable=True),
    sa.Column('record_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_answer_id'], ['question_answer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('school', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('major', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.String(length=100), nullable=False))
        batch_op.drop_index('user_email')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('user_name')
        batch_op.drop_column('user_id')
        batch_op.drop_column('user_major')
        batch_op.drop_column('user_school')
        batch_op.drop_column('user_score')
        batch_op.drop_column('user_password')
        batch_op.drop_column('user_avatar')
        batch_op.drop_column('user_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('user_avatar', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('user_password', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('user_score', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_school', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('user_major', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('user_name', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('user_email', ['user_email'], unique=False)
        batch_op.drop_column('avatar')
        batch_op.drop_column('score')
        batch_op.drop_column('major')
        batch_op.drop_column('school')
        batch_op.drop_column('email')
        batch_op.drop_column('password')
        batch_op.drop_column('name')
        batch_op.drop_column('id')

    op.drop_table('records')
    op.drop_table('question_answer')
    op.drop_table('knowledge_point')
    # ### end Alembic commands ###
